package com.calendarbox.backend.calendar.enums;

public enum CalendarHistoryType {
    CALENDAR_UPDATED,

    SCHEDULE_CREATED,
    SCHEDULE_UPDATED,
    SCHEDULE_DELETED,

    SCHEDULE_PARTICIPANT_ADDED,
    SCHEDULE_PARTICIPANT_REMOVED,

    SCHEDULE_LINK_ADDED,
    SCHEDULE_LINK_REMOVED,

    SCHEDULE_LOCATION_ADDED,
    SCHEDULE_LOCATION_UPDATED,
    SCHEDULE_LOCATION_REMOVED,

    SCHEDULE_ATTACHMENT_ADDED,
    SCHEDULE_ATTACHMENT_REMOVED
}
